config/routes.rb
Rails.application.routes.draw do
  # get 'plants/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'gardens#index'
  resources :gardens do
    resources :plants, except: [:show] do
      collection do
        get :top
      end
    end
  end
  resources :plants, only: [:index, :show, :new, :edit, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:edit, :update]

  def index
    @gardens = Garden.all
  end

  def edit
    @garden = Garden.find(params[:id])
  end

  def update
    @garden.update(garden_params)
    redirect_to gardens_path, notice: 'Garden was successfully updated.'
  end

   def show
    @garden = Garden.find(params[:id])
    #@plants = Plant.where(gardens_id: params[:id])
    @plants = @garden.plants
  end

private

  def set_garden
    @garden = Garden.find(params[:id])
  end

  def garden_params
    params.require(:garden).permit(:name)
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    if params[:garden_id]
      @garden = Garden.find(params[:garden_id])
     # @plants = Plant.where(gardens_id: params[:garden_id])
      @plants = @garden.plants
    else
      @plants = Plant.all
    end
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    @plant.update(plant_params)
    redirect_to plants_path, notice: "garden plant update ok"
  end

  def new
    @plant = Plant.new(params[:id])
  end

  def create
    @plant = Plant.new(plant_params)
    raise
    if @plant.save
      redirect_to garden_plants_path(@plant.garden_id)
    else
      render :new
    end
  end

  private

    def plant_params
      params.require(:plant).permit(:garden_id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/edit.html.erb
<%= form_with model: @garden do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "update" %>
<% end %>

app/views/gardens/index.html.erb
<% @gardens.each do |garden| %>
<%= garden.name%> <%= link_to "Show", garden_path(garden) %> <%= link_to "Edit", edit_garden_path(garden) %> <br>
<% end %>
<%= link_to "Do you wanna plants ?",  plants_path %>

app/views/gardens/show.html.erb
Garden : <%= @garden.name%>
<br>
Plants :<br>
<% @plants.each do |plant| %>
  <%= plant.name%>  <%= link_to "Edit", edit_plant_path(plant) %><br>
<% end %>
<br>
<%= link_to "Add a new plant", new_garden_plant_path(@garden) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EtudeBasique</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/plants/edit.html.erb
<%= form_with model: @plant do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :garden_id %>
  <%= form.submit "update" %>
<% end %>

app/views/plants/index.html.erb
<h1>Plants#index</h1>
<%= @garden.name if  @garden%>
<% @plants.each do |plant| %>
  <%= plant.name%> <%= link_to "Edit", edit_plant_path(plant) %><br>
<% end %>

app/views/plants/new.html.erb
<%= form_with model: @plant do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "update" %>
<% end %>